using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using UnityEngine;

public class Testing : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        ProcessStartInfo start = new ProcessStartInfo();

        string progToRun = @"Assets/Python/test.py";

        int x = 1;

        int y = 2;

        start.FileName = "C:\\ProgramData\\Anaconda3\\python.exe";

        start.Arguments = string.Format("\"{0}\" \"{1}\" \"{2}\"", progToRun, x.ToString(), y.ToString());

        start.UseShellExecute = false;// Do not use OS shell

        start.CreateNoWindow = true; // We don't need new window

        start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back

        start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

        using (Process process = Process.Start(start))

        {

            using (StreamReader reader = process.StandardOutput)

            {

                string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script

                string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                //Debug.Log(scope.GetVariable<string>("filename"));
                //result can be parsed to harvest real results
                print(result);

            }

        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
